MoviesDB/Controllers/MoviesController.cs
using MoviesDB.EF;
using MoviesDB.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MoviesDB.Controllers
{
    public class MoviesController : Controller
    {
        MoviesDBEntities db = new MoviesDBEntities();
        // GET: Movies
        public ActionResult Index()
        {
            return View(db.Entertainments.Where(x => x.IsDeleted == false).ToList());
        }

        // Search for Specific Movie
        public ActionResult _MoviesCatalog(string searchTerm)
        {
            var searchResults = db.Entertainments.Where(m => m.Title.Contains(searchTerm)).Where(x => x.IsDeleted == false).ToList();
            //return PartialView("_MoviesCatalog", searchResults);
            return PartialView("_MoviesCatalogPartial", searchResults);
        }
        // --------------------  sulaiman
        public ActionResult Create()
        {

            ViewBag.genres = new SelectList(db.Genres.Where(x => x.IsDeleted == false), "Id", "Name");
            ViewBag.directors = new SelectList(db.Directors.Where(x => x.isDeleted == false), "Id", "Name");
            //return View();

            // TODO: Need to Fix the Genre to multiple select
            if (Session["UserRole"]?.ToString() == "Admin")
            {
                //    return View(db.Users.ToList());
                //    return View(db.Entertainments.ToList());
                return View();

            }
            //Create AccessDenied Page
            return RedirectToAction("Unauthorized", "Account");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create(Entertainments entertainments, HttpPostedFileBase Image_Cover, List<string> genre, string director)
        public ActionResult Create([Bind(Include = "Title, Description, Release_Year, Duration, Image_Cover, Ratings")] Entertainments entertainments, HttpPostedFileBase Image_Cover, List<string> genre)
        {
            
            if (ModelState.IsValid)
            {
                var addimg = ProcessImageFile(Image_Cover);
                if (addimg == false)
                {
                    // message that the image is not saved.
                    return View(entertainments);
                }
                
                //entertainments.Director_Id = db.Directors.Where(x => x.Name.Contains(director)).FirstOrDefault().Id;
                entertainments.Image_Cover = Image_Cover.FileName;
                db.Entertainments.Add(entertainments);
                db.SaveChanges();
                int newId = entertainments.Id;

                
                foreach(var genreName in genre)
                {
                    Genres genres = db.Genres.FirstOrDefault(g => g.Name == genreName);
                    var movieGenree = new Ent_Genre
                    {
                        Entertainment_Id = newId,
                        Genre_Id = genres.Id
                    };
                    db.Ent_Genre.Add(movieGenree);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            ViewBag.genres = new SelectList(db.Genres.Where(x => x.IsDeleted == false), "Id", "Name");
            ViewBag.directors = new SelectList(db.Directors.Where(x => x.isDeleted == false), "Id", "Name");
            return View(entertainments);
        }

        private bool ProcessImageFile(HttpPostedFileBase imageFile)
        {
            if (imageFile != null && imageFile.ContentLength > 0)
            {
                string fileName = Path.GetFileName(imageFile.FileName);
                string filePath = Path.Combine(Server.MapPath("~/Content/images/movies/"), fileName);
                imageFile.SaveAs(filePath);
                return true;
            }
            return false;
        }
        // GET: Movies/Details/2
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //var entertainments = db.Entertainments.Find(id);
            var entertainments = db.Entertainments.Where(x => x.IsDeleted == false).FirstOrDefault(m => m.Id == id);
            if (entertainments == null)
            {
                return HttpNotFound();
            }
            //var entertainment = db.Entertainments.Find(id).Where(x => x.IsDeleted == false);
            var comments = db.Comments.Where(c => c.EntertainmentId == id).Include(r => r.Users).ToList();

            //var pagedMovieComments = comments.ToPagedList(1, 4);

            var viewModel = new MovieCommentsViewModel
            {
                Entertainment = entertainments,
                Comments = comments
                //Comments = comments
            };

            //return View(entertainments);
            return View(viewModel);
        }
    }
}

MoviesDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/OwlCarousel2-2.3.4-css/owl.carousel.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/select2.min.css" rel="stylesheet" />
    <link href="~/Content/admin.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")
    @* <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>*@

<style>


    .mfp-container {
        height: 35% !important;
    }
    a:hover {
        cursor: pointer;
    }
    .header__actions {
        width: 383px!important;
    }
</style>
</head>


<body>


    <!-- header -->
    <header class="header">
        <div class="header__content">
            <!-- header logo -->
            <a href="index.html" class="header__logo">
                <img src="~/Content/images/user.svg" alt="">
            </a>
            <!-- end header logo -->
            <!-- header menu btn -->
            <button class="header__btn" type="button">
                <span></span>
                <span></span>
                <span></span>
            </button>
            <!-- end header menu btn -->
        </div>
    </header>
    <!-- end header -->
    <!-- sidebar -->
    <div class="sidebar">
        <!-- sidebar logo -->
        <a href="@Url.Action("_GetDashboard", "Account")" class="sidebar__logo">
            <img src="img/logo.svg" alt="">
        </a>
        <!-- end sidebar logo -->
        <!-- sidebar user -->
        <div class="sidebar__user">
            <div class="sidebar__user-img">
                <img src="~/Content/images/user.svg" alt="">
            </div>

            <div class="sidebar__user-title">
                <span> @Session["UserRole"]</span>
                <p>@Session["UserName"]</p>
            </div>
            <a href="@Url.Action("Login", "Account")" class="sidebar__user-btn" type="button">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M4,12a1,1,0,0,0,1,1h7.59l-2.3,2.29a1,1,0,0,0,0,1.42,1,1,0,0,0,1.42,0l4-4a1,1,0,0,0,.21-.33,1,1,0,0,0,0-.76,1,1,0,0,0-.21-.33l-4-4a1,1,0,1,0-1.42,1.42L12.59,11H5A1,1,0,0,0,4,12ZM17,2H7A3,3,0,0,0,4,5V8A1,1,0,0,0,6,8V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V19a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V16a1,1,0,0,0-2,0v3a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V5A3,3,0,0,0,17,2Z" /></svg>
            </a>
        </div>
        <!-- end sidebar user -->
        <!-- sidebar nav -->
        <ul class="sidebar__nav">
            @*<li class="sidebar__nav-item">
                    <a href="index.html" class="sidebar__nav-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,8h0L14,2.74a3,3,0,0,0-4,0L4,8a3,3,0,0,0-1,2.26V19a3,3,0,0,0,3,3H18a3,3,0,0,0,3-3V10.25A3,3,0,0,0,20,8ZM14,20H10V15a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1Zm5-1a1,1,0,0,1-1,1H16V15a3,3,0,0,0-3-3H11a3,3,0,0,0-3,3v5H6a1,1,0,0,1-1-1V10.25a1,1,0,0,1,.34-.75l6-5.25a1,1,0,0,1,1.32,0l6,5.25a1,1,0,0,1,.34.75Z" /></svg> <span>Dashboard</span></a>
                </li>*@
            @*Dashboard*@
            <li class="sidebar__nav-item sidebar__nav-link--active">
                <a id="dashboard" class="sidebar__nav-link dashboard"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M20,8h0L14,2.74a3,3,0,0,0-4,0L4,8a3,3,0,0,0-1,2.26V19a3,3,0,0,0,3,3H18a3,3,0,0,0,3-3V10.25A3,3,0,0,0,20,8ZM14,20H10V15a1,1,0,0,1,1-1h2a1,1,0,0,1,1,1Zm5-1a1,1,0,0,1-1,1H16V15a3,3,0,0,0-3-3H11a3,3,0,0,0-3,3v5H6a1,1,0,0,1-1-1V10.25a1,1,0,0,1,.34-.75l6-5.25a1,1,0,0,1,1.32,0l6,5.25a1,1,0,0,1,.34.75Z"></path></svg> <span>Dashboard</span></a>
            </li>
            @* Movies List *@
            <li class="sidebar__nav-item">
                <a id="allMoviesButton" class="sidebar__nav-link allMoviesButton">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M10,13H3a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V14A1,1,0,0,0,10,13ZM9,20H4V15H9ZM21,2H14a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V3A1,1,0,0,0,21,2ZM20,9H15V4h5Zm1,4H14a1,1,0,0,0-1,1v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V14A1,1,0,0,0,21,13Zm-1,7H15V15h5ZM10,2H3A1,1,0,0,0,2,3v7a1,1,0,0,0,1,1h7a1,1,0,0,0,1-1V3A1,1,0,0,0,10,2ZM9,9H4V4H9Z" /></svg>
                    <span>Catalog</span>
                </a>
            </li>
            @* Users *@
            <li class="sidebar__nav-item">
                <a id="allUsersButton" class="sidebar__nav-link allUsersButton">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M12.3,12.22A4.92,4.92,0,0,0,14,8.5a5,5,0,0,0-10,0,4.92,4.92,0,0,0,1.7,3.72A8,8,0,0,0,1,19.5a1,1,0,0,0,2,0,6,6,0,0,1,12,0,1,1,0,0,0,2,0A8,8,0,0,0,12.3,12.22ZM9,11.5a3,3,0,1,1,3-3A3,3,0,0,1,9,11.5Zm9.74.32A5,5,0,0,0,15,3.5a1,1,0,0,0,0,2,3,3,0,0,1,3,3,3,3,0,0,1-1.5,2.59,1,1,0,0,0-.5.84,1,1,0,0,0,.45.86l.39.26.13.07a7,7,0,0,1,4,6.38,1,1,0,0,0,2,0A9,9,0,0,0,18.74,11.82Z" /></svg>
                    <span>Users</span>
                </a>
            </li>


            <li class="sidebar__nav-item">
                <a href="@Url.Action("Index","Movies")" class="sidebar__nav-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M17,11H9.41l3.3-3.29a1,1,0,1,0-1.42-1.42l-5,5a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l5,5a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L9.41,13H17a1,1,0,0,0,0-2Z" /></svg> <span>Back to MoviesDB</span></a>
            </li>
        </ul>
        <!-- end sidebar nav -->
    </div>
    <!-- end sidebar -->
    <div id="content">
        @RenderBody()
    </div>

    <!-- end modal status -->
    <!-- JS -->
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")*@
    @*@Scripts.Render("~/bundles/magnific-popup")*@
    @*@Styles.Render("~/Content/magnific-popup")*@
    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@

    @*@RenderSection("scripts", required: false)*@

    @*@Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/magnific-popup")
        @Styles.Render("~/Content/magnific-popup")*@
    @*<script src="~/Scripts/jquery-3.5.1.min.js"></script>*@
        <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
        @*<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>*@

    <script>

        $(document).ready(function() {
            //$('#allMoviesButton').click(function() {
            $('.allMoviesButton').click(function() {
                $.ajax({
                    url: '@Url.Action("_GetAllMovies")',
                    type: 'GET',
                    success: function(result) {
                        $('#content').html(result);
                    },
                    error: function() {
                        // Handle error
                    }
                });
            });
        });

        $(document).ready(function () {
            $('#dashboard').click(function() {
                $.ajax({
                    url: '@Url.Action("_GetDashboard")',
                    type: 'GET',
                    success: function(result) {
                        $('#content').html(result);
                    },
                    error: function() {
                        // Handle error
                    }
                });
            });
        });
        $(document).ready(function() {
            $('.allUsersButton').click(function() {
                $.ajax({
                    url: '@Url.Action("_AllUsers")',
                    type: 'GET',
                    success: function(result) {
                        $('#content').html(result);
                    },
                    error: function() {
                        // Handle error
                    }
                });
            });
        });

    $(document).ready(function () {
    $('.activate-user').click(function (e) {
      console.log("activate")
    // Add the HTML content to the page
      var userId = $(this).data("userid");
      var isActivated = $(this).data("isactivated");
    $('body').prepend(`
      <div class="at mfp-bg my-mfp-zoom-in mfp-ready" id = "popup1"></div>
      <div class="at mfp-wrap mfp-close-btn-in mfp-auto-cursor my-mfp-zoom-in mfp-ready" id = "popup2" tabindex="-1" style="overflow: hidden auto; ">
        <div class="mfp-container mfp-inline-holder">
          <div class="mfp-content">
            <div id="modal-status" class="zoom-anim-dialog modal">
              <h6 class="modal__title">Status change</h6>
              <p class="modal__text">Are you sure you want to immediately change the status?</p>
              <div class="modal__btns">
                <button class="modal__btn modal__btn--apply" type="button">Apply</button>
                <button class="modal__btn modal__btn--dismiss cancel-button" type="button">Dismiss</button>
              </div>
              <button title="Close (Esc)" type="button" class="mfp-close">×</button>
            </div>
          </div>
        </div>
      </div>
    `);

    // Handle the "Apply" button click
      $('.modal__btn--apply').click(function () {
          console.log("apply btn");
          //var userId = $(this).data("userid");
          //var userId = $(this).closest('.mfp-wrap').find('.activate-user').data("userid");
          console.log(userId);
          //var isActivated = $(this).data("isactivated");
          //var isActivated = $(this).closest('.mfp-wrap').find('.activate-user').data("isactivated");
          console.log(isActivated);

          $.ajax({
            url: '@Url.Action("ActivateOrDeactivateUser", "Account")',
            type: 'POST',
            data: { userId: userId, isActivated: isActivated },
            success: function (response) {
              // Refresh the page or perform any other necessary actions
              // alert('User activated successfully!');
              location.reload(); // Refresh the page
            },
            error: function (xhr, status, error) {
              // Handle error response here
              // For example, display an error message
              alert('Error activating user: ' + error);
            }
          });
    });

    // Handle the "Dismiss" button click
    $('.cancel-button').click(function() {
          $('.at').hide();
        });
      });
    });


    $(document).ready(function () {
            $('.sidebar__nav-link').click(function () {
                $('.sidebar__nav-link').removeClass('sidebar__nav-link--active');
                $(this).addClass('sidebar__nav-link--active');
            });
        });


    </script>

</body>
</html>

MoviesDB/Views/Shared/_MyLayout.cshtml

@{
    Layout = null;
    string userRole = Session["UserRole"]?.ToString();
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Welcome to Movies DB</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/admin.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .log-in {
            margin-left: 185px;
        }

        .log-out {
            margin-left: 140px;
        }
    </style>
</head>
<body>
    <!--Header-->
    <!-- header (relative style) -->
    <header class="header header--static">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="header__content">
                        @*<button class="header__menu" type="button">
                                <span></span>
                                <span></span>
                                <span></span>
                            </button>*@

                        <a href="@Url.Action("Index","Movies")" class="header__logo">
                            @*<img src="img/logo.svg" alt="Movies & TV Shows, Online cinema HTML Template">*@
                            <img src="~/Content/images/Screenshot_2023-06-21_200801-removebg-preview.png" />
                        </a>

                        @*<ul class="header__nav">
                                <li class="header__nav-item">
                                    <a class="header__nav-link" href="index.html">Home</a>
                                </li>
                                <li class="header__nav-item">
                                    <a class="header__nav-link" href="#" role="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catalog <svg width="4" height="4" viewbox="0 0 4 4" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1.93893 3.30334C1.08141 3.30334 0.384766 2.60669 0.384766 1.75047C0.384766 0.894254 1.08141 0.196308 1.93893 0.196308C2.79644 0.196308 3.49309 0.894254 3.49309 1.75047C3.49309 2.60669 2.79644 3.30334 1.93893 3.30334Z"></path></svg></a>

                                    <ul class="dropdown-menu header__nav-menu" aria-labelledby="dropdownMenu1">
                                        <li><a href="catalog.html">Catalog</a></li>
                                        <li><a href="catalog.html">Hollywood</a></li>
                                        <li><a href="catalog.html">Bollywood</a></li>
                                        <li><a href="catalog.html">Pakistani</a></li>
                                    </ul>
                                </li>
                                <li class="header__nav-item">
                                    <a class="header__nav-link" href="about.html">About Us</a>
                                </li>
                                <li class="header__nav-item">
                                    <a class="header__nav-link header__nav-link--live" href="contacts.html">Contact<svg width="12" height="12" viewbox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="6" cy="4" r="4" fill="#EB5757" fill-opacity="0.5"></circle><g filter="url(#filter0_d)"><circle cx="6" cy="4" r="2" fill="#EB5757"></circle></g><defs><filter id="filter0_d" x="0" y="0" width="12" height="12" filterunits="userSpaceOnUse" color-interpolation-filters="sRGB"><feflood flood-opacity="0" result="BackgroundImageFix"></feflood><fecolormatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"></fecolormatrix><feoffset dy="2"></feoffset><fegaussianblur stddeviation="2"></fegaussianblur><fecolormatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.3 0"></fecolormatrix><feblend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow"></feblend><feblend mode="normal" in="SourceGraphic" in2="effect1_dropShadow" result="shape"></feblend></filter></defs></svg></a>
                                </li>
                                <li class="header__nav-item">
                                    <a class="header__nav-link header__nav-link--more" href="#" role="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <svg width="25" height="25" viewbox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.93893 14.3033C6.08141 14.3033 5.38477 13.6067 5.38477 12.7505C5.38477 11.8943 6.08141 11.1963 6.93893 11.1963C7.79644 11.1963 8.49309 11.8943 8.49309 12.7505C8.49309 13.6067 7.79644 14.3033 6.93893 14.3033Z"></path><path d="M12.7501 14.3033C11.8926 14.3033 11.1959 13.6067 11.1959 12.7505C11.1959 11.8943 11.8926 11.1963 12.7501 11.1963C13.6076 11.1963 14.3042 11.8943 14.3042 12.7505C14.3042 13.6067 13.6076 14.3033 12.7501 14.3033Z"></path><path d="M18.5608 14.3033C17.7032 14.3033 17.0066 13.6067 17.0066 12.7505C17.0066 11.8943 17.7032 11.1963 18.5608 11.1963C19.4183 11.1963 20.1149 11.8943 20.1149 12.7505C20.1149 13.6067 19.4183 14.3033 18.5608 14.3033Z"></path></svg>
                                    </a>

                                    <ul class="dropdown-menu header__nav-menu header__nav-menu--scroll" aria-labelledby="dropdownMenu3">
                                        <li><a href="privacy.html">Privacy policy</a></li>

                                    </ul>
                                </li>
                            </ul>*@

                        <div class="header__actions">
                            @if (Session["UserName"] != null)
                            {
                                <a href="@Url.Action("Logout","Account")" class="header__user">
                                    <span class="log-out">Log out</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24"><path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"></path></svg>
                                </a>
                                if (userRole == "Admin")
                                {
                                    <a href="@Url.Action("Index","Account")" class="header__user">
                                        <span>Admin Account</span>
                                    </a>
                                }
                            }
                            else
                            {
                                <a href="@Url.Action("Login","Account")" class="header__user">
                                    <span class="log-in">Log in</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24"><path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"></path></svg>
                                </a>
                                <a href="@Url.Action("Register","Account")" class="header__user">
                                    <span>Register</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24"><path d="M20,12a1,1,0,0,0-1-1H11.41l2.3-2.29a1,1,0,1,0-1.42-1.42l-4,4a1,1,0,0,0-.21.33,1,1,0,0,0,0,.76,1,1,0,0,0,.21.33l4,4a1,1,0,0,0,1.42,0,1,1,0,0,0,0-1.42L11.41,13H19A1,1,0,0,0,20,12ZM17,2H7A3,3,0,0,0,4,5V19a3,3,0,0,0,3,3H17a3,3,0,0,0,3-3V16a1,1,0,0,0-2,0v3a1,1,0,0,1-1,1H7a1,1,0,0,1-1-1V5A1,1,0,0,1,7,4H17a1,1,0,0,1,1,1V8a1,1,0,0,0,2,0V5A3,3,0,0,0,17,2Z"></path></svg>
                                </a>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- end header -->



    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @*<footer class="footer">
        <div class="container">

            <div class="row">
                <div class="col-12">
                    <div class="footer__content">

                        <small class="footer__copyright">© MoviesDB, 2023.</small>
                    </div>
                </div>
            </div>
        </div>
    </footer>*@
</body>
</html>
